export const kycRejectReasonsEN: Record<string, string> = {
	FACE_NOT_LIVE: "Blurry selfie",
	FACE_NOT_FOUND: "No face on the selfie",
	DOCUMENT_FACE_NOT_FOUND: "No face on the document",
	DOCUMENT_FRONT_MISSING: "Front side of the document missing",
	DOCUMENT_BACK_MISSING: "Back side of the document missing",
	FACE_PREVIOUSLY_ONBOARDED: "Selfie face matches another user",
	MISSING_NAME: "Missing name on the document",
	MISSING_DOCUMENT_NUMBER: "Missing identification number on the document",
	FACE_LIVENESS_TOO_FAR_FROM_CAMERA: "Face too far from the camera",
	FACE_MISMATCH: "Mismatch between selfie face and document face",
	NAME_MISMATCH: "Mismatch between the name provided and the document",
	BIRTHDATE_MISMATCH:
		"Mismatch between the provided birth date and the document",
	DOCUMENT_NUMBER_MISMATCH:
		"Mismatch between the provided identification number and the document",
	UNRECOGNIZED_DOCUMENT: "Unrecognized document",
	MISSING_EMAIL: "Missing email",
	MISSING_PHONE_NUMBER: "Missing phone number",
	WRONG_NAME: "Incorrect name",
	WRONG_EMAIL: "Incorrect email",
	WRONG_PHONE_NUMBER: "Incorrect phone number",
	WRONG_IDENTITY_NUMBER: "Incorrect identity number",
	EMAIL_NOT_VERIFIED: "Email not verified",
	PHONE_NUMBER_NOT_VERIFIED: "Phone number not verified",
	IDENTITY_FRONT_BACK_DIFFERENT:
		"Front identity document different from the back",
	SCANNED_DOCUMENT_NOT_AUTHENTIC: "Scanned document photo not authentic",
	FRONT_DOCUMENT_SELFIE_MISMATCH:
		"Mismatch between the front document and the selfie",
	BACK_DOCUMENT_FRONT_SELFIE_MISMATCH:
		"Mismatch between the back document and the front or selfie",
	FRONT_BLURRY: "Front unclear",
	BACK_BLURRY: "Back unclear",
	NAME_ORDER_NOT_RESPECTED: "Name order on the document not respected",
	INCOMPLETE_NAME: "Incomplete name",
	PASSPORT_FIRST_PAGE_NOT_VISIBLE: "First page of the passport not visible",
	FRONT_DOCUMENT_UNREADABLE: "Front document/photo unreadable",
	UNDERAGE: "Not old enough",
};

// Version française si besoin
export const kycRejectReasonsFR: Record<string, string> = {
	FACE_NOT_LIVE: "Selfie flou",
	FACE_NOT_FOUND: "Visage non détecté sur le selfie",
	DOCUMENT_FACE_NOT_FOUND: "Visage non détecté sur le document",
	DOCUMENT_FRONT_MISSING: "Recto du document manquant",
	DOCUMENT_BACK_MISSING: "Verso du document manquant",
	FACE_PREVIOUSLY_ONBOARDED:
		"Visage déjà enregistré pour un autre utilisateur",
	MISSING_NAME: "Nom manquant sur le document",
	MISSING_DOCUMENT_NUMBER: "Numéro d'identification manquant sur le document",
	FACE_LIVENESS_TOO_FAR_FROM_CAMERA: "Visage trop éloigné de la caméra",
	FACE_MISMATCH: "Non-correspondance entre le selfie et le document",
	NAME_MISMATCH: "Non-correspondance du nom",
	BIRTHDATE_MISMATCH: "Non-correspondance de la date de naissance",
	DOCUMENT_NUMBER_MISMATCH: "Non-correspondance du numéro d'identification",
	UNRECOGNIZED_DOCUMENT: "Document non reconnu",
	MISSING_EMAIL: "Email manquant",
	MISSING_PHONE_NUMBER: "Numéro de téléphone manquant",
	WRONG_NAME: "Nom incorrect",
	WRONG_EMAIL: "Email incorrect",
	WRONG_PHONE_NUMBER: "Numéro de téléphone incorrect",
	WRONG_IDENTITY_NUMBER: "Numéro d'identité incorrect",
	EMAIL_NOT_VERIFIED: "Email non vérifié",
	PHONE_NUMBER_NOT_VERIFIED: "Numéro de téléphone non vérifié",
	IDENTITY_FRONT_BACK_DIFFERENT: "Recto et verso du document différents",
	SCANNED_DOCUMENT_NOT_AUTHENTIC: "Document scanné non authentique",
	FRONT_DOCUMENT_SELFIE_MISMATCH:
		"Non-correspondance entre le recto et le selfie",
	BACK_DOCUMENT_FRONT_SELFIE_MISMATCH:
		"Non-correspondance entre le verso et le recto ou selfie",
	FRONT_BLURRY: "Recto flou",
	BACK_BLURRY: "Verso flou",
	NAME_ORDER_NOT_RESPECTED: "Ordre du nom non respecté",
	INCOMPLETE_NAME: "Nom incomplet",
	PASSPORT_FIRST_PAGE_NOT_VISIBLE: "Première page du passeport non visible",
	FRONT_DOCUMENT_UNREADABLE: "Recto illisible",
	UNDERAGE: "Mineur",
};
